theme: jekyll-theme-minimal
title: Moonshot Solutions
description: Profitable trading algos for day traders and institutions.
logo: https://raw.githubusercontent.com/MoonshotSolutions/moonshotsolutions.github.io/main/assets/Version_4_Inverted.png
show-downloads: true
