theme: jekyll-theme-minimal
title: Moonshot Solutions
description: Profitable trading algos for day traders and institutions.
logo: https://github.com/MoonshotSolutions/moonshotsolutions.github.io/blob/main/assets/Version_4_Inverted.png
show-downloads: false
